install.packages(ISLR)

#Chapter3-Prob9
library(ISLR)
Auto=read.table("Auto.data" , header=TRUE)
fix(Auto)
names(Auto)
dim(Auto)
str(Auto)
summary(Auto)
pairs(~.,data=Auto , main="Scatterplot matrix for Auto")
Auto_fix <- subset(Auto , select= -name)
names(Auto_fix)
Auto_cor <- cor(Auto_fix, use="complete.obs" , method="pearson")
install.packages(corrplot)
library(corrplot)
corrplot(Auto_cor)
lm.fit = lm(data=Auto_fix , mpg ~ .)
summary(lm.fit)
par(mfrow = c(2,2))
jpeg("R-lmPlot.jpg")
par(mfrow = c(2,2))
plot(lm.fit)
dev.off()
